### ISSUE TITLE
How to use the SPARQL endpoint?

### ISSUE THREAD

**Issue by VladimirAlexiev** [american-art/semantic-hosting#7]
http://data.americanartcollaborative.org/sparql
Error 404: Service Description: /american-art/query
Fuseki - version 2.4.0 (Build date: 2016-05-10T11:59:39+0000)

@caknoblock Please bring it up. Some things I need to check that I can't do by browsing alone! Need it asap, my deadline is 1 Mar.

http://review.americanartcollaborative.org does return data (though not very often),
eg [primary title](http://review.americanartcollaborative.org/entity/E22_Man-Made_Object#field_0-search_0) of object http://data.americanartcollaborative.org/npg/object/49748.
@workergnome where does it get the data from?

**Comment by VladimirAlexiev** [comment]
I'm wrong, http://data.americanartcollaborative.org/sparql?query=abc returns something (a syntax error as expected).
Is there a GUI for it? Else I'll just use yasgui.

**Comment by VladimirAlexiev** [comment]
eg this searches for references (P70_documents):
http://yasgui.org/#query=PREFIX+crm%3A+%3Chttp%3A%2F%2Fwww.cidoc-crm.org%2Fcidoc-crm%2F%3E%0Aselect+*+%7B%0A++%3Fx+crm%3AP70_documents+%3Fy%0A%7D&contentTypeConstruct=text%2Fturtle&contentTypeSelect=application%2Fsparql-results%2Bjson&endpoint=http%3A%2F%2Fdata.americanartcollaborative.org%2Fsparql&requestMethod=GET&tabTitle=Query&headers=%7B%7D&outputFormat=table

**Comment by workergnome** [comment]
(Doesn't appear to be a GUI for it.  I've been using other tools.)

**Comment by VladimirAlexiev** [comment]
yasgui works nicely
